SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `Car`;
CREATE TABLE `Car` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SaleCategory` varchar(255) DEFAULT NULL,
  `Make` varchar(255) DEFAULT NULL,
  `Model` varchar(255) DEFAULT NULL,
  `Branch` varchar(255) DEFAULT NULL,
  `Sold_Amount` decimal(10,2) DEFAULT NULL,
  `Age_Comp_Months` int(11) DEFAULT NULL,
  `Odometer` int(11) DEFAULT NULL,
  `OverallCondition` varchar(255) DEFAULT NULL,
  `YearGroup` int(11) DEFAULT NULL,
  `Sold_Date` date DEFAULT NULL,
  `FuelTypeDescription` varchar(255) DEFAULT NULL,
  `GearTypeDescription` varchar(255) DEFAULT NULL,
  `Description` varchar(255) DEFAULT NULL,
  `BodyStyleDescription` varchar(255) DEFAULT NULL,
  `drivedescription` varchar(255) DEFAULT NULL,
  `VehicleDescription` varchar(255) DEFAULT NULL,
  `ConditionDescription` varchar(500) DEFAULT NULL,
  `OptionsAccessories` varchar(500) DEFAULT NULL,
  `LogBooks` varchar(255) DEFAULT NULL,
  `KeysStatus` varchar(255) DEFAULT NULL,
  `TyreFrontNearCondition` varchar(255) DEFAULT NULL,
  `TyreFrontOffCondition` varchar(255) DEFAULT NULL,
  `TyreRearNearCondition` varchar(255) DEFAULT NULL,
  `TyreRearOffCondition` varchar(255) DEFAULT NULL,
  `TyreSpareCondition` varchar(255) DEFAULT NULL,
  `Colour` varchar(255) DEFAULT NULL,
  `EngineDescription` varchar(255) DEFAULT NULL,
  `GearNum` int(11) DEFAULT NULL,
  `BadgeDescription` varchar(255) DEFAULT NULL,
  `FuelDeliveryDescription` varchar(255) DEFAULT NULL,
  `InductionDescription` varchar(255) DEFAULT NULL,
  `OwnerManualStatus` varchar(255) DEFAULT NULL,
  `SaleType` varchar(255) DEFAULT NULL,
  `Division` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `Car` (`id`, `SaleCategory`, `Make`, `Model`, `Branch`, `Sold_Amount`, `Age_Comp_Months`, `Odometer`, `OverallCondition`, `YearGroup`, `Sold_Date`, `FuelTypeDescription`, `GearTypeDescription`, `Description`, `BodyStyleDescription`, `drivedescription`, `VehicleDescription`, `ConditionDescription`, `OptionsAccessories`, `LogBooks`, `KeysStatus`, `TyreFrontNearCondition`, `TyreFrontOffCondition`, `TyreRearNearCondition`, `TyreRearOffCondition`, `TyreSpareCondition`, `Colour`, `EngineDescription`, `GearNum`, `BadgeDescription`, `FuelDeliveryDescription`, `InductionDescription`, `OwnerManualStatus`, `SaleType`, `Division`) VALUES
(1,	'Dealership',	'Audi',	'A5',	'Canning Vale (WA)',	0.00,	101,	61624,	'Above Average',	2015,	'2023-11-09',	'Petrol',	'Automatic',	'8T MY15 Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2015',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Black',	'2.0',	7,	NULL,	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(2,	'Auction',	'Audi',	'A5',	'Bibra Lake, Perth (WA)',	0.00,	118,	182605,	'Average',	2013,	'2023-11-08',	'Petrol',	'Automatic',	'8T MY14 Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2013',	'Minor Paint Chips and Small Scratches Visible ,Minor Dents ,Bird Stains ,Bird Stains ,Bent Edge ,Minor Dents ,Minor Dents ,Minor Dents ,Minor Dents ,Bird Stains ,Missing 1 Service ,Minor Dents ,Alloy Wheel Dented/Scraped ,Pitted ,Paint Cracked ,Paint Flaking ,Scrapes ,Scratches ,Major Dents ,Scrapes ,Scratches ,Bent Edge ,Dents ,Scrapes ,Scratches ,Spare Key Missing ,Bonnet Strut Inoperative ',	'ABS, Traction Control, Cent.Lock, P/Steer, P/Wind, CD Player, Airbag Side Various, ABS, Airbag Dual, Airbag Side Various, Aircond., Alloy Wheels, AWD, Bluetooth, CD Player, Cent.Lock, Cru. Cont, Dual Zone Climate Control, Fitted with Standard Factory Accessories, GPS Navigation, Heated Seats, Jack, Keyless Entry, Keyless Start, P/Seats, P/Steer, P/Wind, Paddle Gear Shift, Park Sensors, Radio, Reverse Camera, Sunroof, Traction Control, Turbo, Wood Grain Look Inserts',	'Partial Service History',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'Space Saver',	'Blue',	'2.0',	7,	NULL,	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(3,	'Dealership',	'Audi',	'A5',	'Wright (ACT)',	0.00,	158,	105674,	'Excellent',	2010,	'2023-11-08',	'Petrol',	'CVT',	'8T MY10 Coupe 2dr multitronic 8sp 2.0T',	'Coupe',	'Front Wheel Drive',	'Audi A5 2010',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Silver Or Chrome',	'2.0',	8,	NULL,	'Multi-Point Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(4,	'Dealership',	'Audi',	'A5',	'Sydney Olympic Park (NSW)',	0.00,	111,	90865,	'Excellent',	2014,	'2023-11-04',	'Petrol',	'Automatic',	'8T MY14 S Line Competition Coupe 2dr S tronic 7sp quattro 2.0T',	'Coupe',	'4x4',	'Audi A5 2014',	NULL,	'Sports Suspension - S line',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Blue',	'2.0',	7,	'S Line Competition',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(5,	'Dealership',	'Audi',	'A5',	'Kalgoorlie (WA)',	0.00,	189,	119700,	'Excellent',	2008,	'2023-11-03',	'Petrol',	'CVT',	'8T Coupe 2dr multitronic 8sp 3.2i',	'Coupe',	'Front Wheel Drive',	'Audi A5 2008',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Grey',	'3.2',	8,	NULL,	'Multi-Point Injection',	'Aspirated',	NULL,	NULL,	'Motor Vehicles'),
(6,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	79,	96322,	'Average',	2017,	'2023-11-02',	'Petrol',	'Automatic',	'F5 MY17 sport Coupe 2dr S tronic 7sp 2.0T',	'Coupe',	'Front Wheel Drive',	'Audi A5 2017',	'Minor Paint Chips and Small Scratches Visible ,Minor Pitting Visible ,Scrapes ,Alloy Wheel Dented/Scraped ',	'Airbag Side Various, Auxilliary Lights, ABS, Airbag Dual, Airbag Side Various, Alloy Wheels, Bluetooth, Cent.Lock, Climate Control, Cru. Cont, GPS Navigation, Heated Seats, Keyless Start, P/Seats, P/Steer, P/Wind, Paddle Gear Shift, Park Sensors, Radio, Reverse Camera, Sunroof, ABS, Cent.Lock, P/Steer, P/Wind',	'Online Service History - Contact Manufacturer',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'Space Saver',	'White',	'2.0',	7,	'sport',	'Direct & Multi-Point Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(7,	'Wholesale',	'Audi',	'A5',	'Parramatta (NSW)',	0.00,	40,	33679,	'Above Average',	2020,	'2023-11-02',	'Petrol',	'Automatic',	'F5 MY20 45 TFSI S line Coupe 2dr S tronic 7sp quattro 2.0T',	'Coupe',	'4x4',	'Audi A5 2020',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Grey',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(8,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	5,	959,	'Excellent',	2022,	'2023-10-26',	'Petrol',	'Automatic',	'F5 MY23 45 TFSI S line Coupe 2dr S tronic 7sp quattro 2.0T',	'Coupe',	'4x4',	'Audi A5 2022',	'Bird Stains ',	NULL,	'Online Service History - Contact Manufacturer',	'Keys',	'Good',	'Good',	'Good',	'Good',	'Space Saver',	'Grey',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(9,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	27,	7907,	'Below Average',	2021,	'2023-10-26',	'Petrol',	'Automatic',	'F5 MY21 45 TFSI S line Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2021',	'Side Wall Damaged ,Side Wall Damaged ,Alloy Wheel Dented/Scraped ,Minor Paint/Stone Chips ,Scratches ,Alloy Wheel Dented/Scraped ,Minor Dent ,Minor Scratches ,Minor Dents ,Minor Scratches ,Scrapes ,Scratches ,Side Wall Damaged ,Side Wall Damaged ,Alloy Wheel Dented/Scraped ,Scratches ,Scuffs ,Scratches ,Minor Dents ,Scratches ,Minor Scratches ,Scratches ,Alloy Wheel Dented/Scraped ,Minor Paint Chips and Small Scratches Visible ',	NULL,	'Online Service History - Contact Manufacturer',	'Keys',	'Bad',	'Bad',	'Bad',	'Bad',	'Space Saver',	'Black',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(10,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	27,	23915,	'Average',	2021,	'2023-10-26',	'Petrol',	'Automatic',	'F5 MY21 45 TFSI S line Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2021',	'Minor Paint/Stone Chips ,Alloy Wheel Dented/Scraped ',	'Fitted with Standard Factory Accessories',	'Online Service History - Contact Manufacturer',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'Space Saver',	'White',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(11,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	27,	20948,	'Good',	2021,	'2023-10-26',	'Petrol',	'Automatic',	'F5 MY21 45 TFSI S line Cabriolet 2dr S tronic 7sp quattro 2.0T',	'Cabriolet',	'4x4',	'Audi A5 2021',	'Minor Scrapes ,Alloy Wheel Dented/Scraped ',	NULL,	'Online Service History - Contact Manufacturer',	'Keys',	'Good',	'Good',	'Good',	'Good',	'No Spare Fitted With This Model',	'White',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(12,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	27,	29246,	'Good',	2021,	'2023-10-26',	'Petrol',	'Automatic',	'F5 MY21 45 TFSI S line Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2021',	'Minor Scratches All Over ',	'Fitted with Standard Factory Accessories',	'Online Service History - Contact Manufacturer',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'Space Saver',	'Black',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(13,	'Auction',	'Audi',	'A5',	'Sunshine, Melbourne (VIC)',	0.00,	33,	24395,	'Average',	2020,	'2023-10-26',	'Petrol',	'Automatic',	'F5 MY21 45 TFSI S line Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2020',	'Alloy Wheel Dented/Scraped ,Alloy Wheel Dented/Scraped ,Alloy Wheel Dented/Scraped ',	'Fitted with Standard Factory Accessories',	'Online Service History - Contact Manufacturer',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'Space Saver',	'White',	'2.0',	7,	'45 TFSI S line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(14,	'Fixed Price',	'Audi',	'A5',	'Belmore, Sydney (NSW)',	0.00,	77,	93170,	'Above Average',	2017,	'2023-10-12',	'Petrol',	'Automatic',	'F5 MY17 sport Sportback 5dr S tronic 7sp quattro 2.0T',	'Hatchback',	'4x4',	'Audi A5 2017',	'Service Books Missing ,Minor Paint Chips and Small Scratches Visible ',	'ABS, Traction Control, Cent.Lock, P/Steer, P/Wind, CD Player, Airbag Side Various, ABS, Airbag Dual, Airbag Side Various, Aircond., Alloy Wheels, AWD, Blind Spot Monitor, CD Player, Cent.Lock, Climate Control, Cru. Cont, Digital Radio, GPS Navigation, Heads Up Display, Keyless Entry, Keyless Start, P/Seats, P/Steer, P/Wind, Paddle Gear Shift, Park Sensors - Front, Park Sensors - Rear, Premium Sound System, Radio, Reverse Camera, Sunroof, Traction Control, Turbo, Xenon Headlights',	'No Log Books/No Service History',	'Keys',	'Good',	'Good',	'Good',	'Good',	'Space Saver',	'Grey',	'2.0',	7,	'sport',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(15,	'Dealership',	'Audi',	'A3',	'Bankstown (NSW)',	0.00,	80,	13811,	'Excellent',	2017,	'2023-11-09',	'Petrol',	'Automatic',	'8V MY17 Cabriolet 2dr S tronic 7sp 1.4T (CoD)',	'Cabriolet',	'Front Wheel Drive',	'Audi A3 2017',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'White',	'1.4',	7,	NULL,	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(16,	'Dealership',	'Audi',	'A3',	'Roxburgh Park (VIC)',	0.00,	105,	56540,	'Above Average',	2015,	'2023-11-09',	'Petrol',	'Automatic',	'8V MY15 Attraction Sedan 4dr S tronic 7sp 1.4T (CoD)',	'Sedan',	'Front Wheel Drive',	'Audi A3 2015',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Black',	'1.4',	7,	'Attraction',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(17,	'Dealership',	'Audi',	'A3',	'Brabham (WA)',	0.00,	105,	158689,	'Above Average',	2015,	'2023-11-07',	'Petrol',	'Automatic',	'8V MY15 Attraction Sedan 4dr S tronic 7sp 1.4T (CoD)',	'Sedan',	'Front Wheel Drive',	'Audi A3 2015',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Black',	'1.4',	7,	'Attraction',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(18,	'Wholesale',	'Audi',	'A3',	'Richmond (VIC)',	0.00,	50,	27011,	'Above Average',	2019,	'2023-11-07',	'Petrol',	'Automatic',	'8V MY19 35 TFSI Sportback 5dr S tronic 7sp 1.4T',	'Hatchback',	'Front Wheel Drive',	'Audi A3 2019',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Grey',	'1.4',	7,	'35 TFSI',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(19,	'Wholesale',	'Audi',	'A1',	'Mayfield West (NSW)',	0.00,	91,	95115,	'Above Average',	2016,	'2023-11-10',	'Petrol',	'Automatic',	'8X MY16 Sport Sportback 5dr S tronic 7sp 1.4T',	'Hatchback',	'Front Wheel Drive',	'Audi A1 2016',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'White',	'1.4',	7,	'Sport',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(20,	'Auction',	'Audi',	'A1',	'Sunshine, Melbourne (VIC)',	0.00,	9,	4070,	'Average',	2022,	'2023-10-26',	'Petrol',	'Automatic',	'GB MY23 30 TFSI Sportback 5dr S tronic 7sp 1.0T',	'Hatchback',	'Front Wheel Drive',	'Audi A1 2022',	'Bird Stains ',	'ABS, Traction Control, Cent.Lock, P/Steer, P/Wind, Airbag Side Various, ABS, Airbag Dual, Airbag Side Various, Aircond., Alloy Wheels, Cent.Lock, Cru. Cont, Heated Seats, Keyless Entry, Keyless Start, P/Steer, P/Wind, Park Sensors - Front, Park Sensors - Rear, Radio, Reverse Camera, Traction Control, Turbo',	'Online Service History - Contact Manufacturer',	'Keys',	'Good',	'Good',	'Good',	'Good',	'No Spare Fitted With This Model',	'Black',	'1.0',	7,	'30 TFSI',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(21,	'Wholesale',	'BMW',	'1 Series',	'Mayfield West (NSW)',	0.00,	141,	48116,	'Above Average',	2011,	'2023-11-10',	'Petrol',	'Automatic',	'F20 116i Hatchback 5dr Spts Auto 8sp 1.6T',	'Hatchback',	'Rear Wheel Drive',	'BMW 1 Series 2011',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Black',	'1.6',	8,	'116i',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(22,	'Dealership',	'BMW',	'1 Series',	'Parkdale (VIC)',	0.00,	226,	140838,	'Excellent',	2005,	'2023-11-09',	'Petrol',	'Automatic',	'E87 120i Hatchback 5dr Auto 6sp 2.0i',	'Hatchback',	'Rear Wheel Drive',	'BMW 1 Series 2005',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Blue',	'2.0',	6,	'120i',	'Multi-Point Injection',	'Aspirated',	NULL,	NULL,	'Motor Vehicles'),
(23,	'Auction',	'BMW',	'2 Series',	'Sunshine, Melbourne (VIC)',	0.00,	101,	27525,	'Above Average',	2015,	'2023-11-06',	'Petrol',	'Automatic',	'F45 218i Luxury Line Active Tourer 5dr Steptronic 6sp 1.5T',	'Hatchback',	'Front Wheel Drive',	'BMW 2 Series 2015',	'Minor Paint Chips & Small Scratches Visible ,Pitted ',	'ABS, Cent.Lock, P/Steer, P/Wind, CD Player, Airbag Side Various, Auxilliary Lights, ABS, Airbag Dual, Airbag Side Various, Alloy Wheels, Bluetooth, CD Player, Cent.Lock, Climate Control, Cru. Cont, GPS Navigation, Keyless Start, P/Steer, P/Wind, Park Sensors - Front, Park Sensors - Rear, Radio, Reverse Camera',	'Onboard Service History - Complete',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'No Spare Fitted With This Model',	'White',	'1.5',	6,	'218i Luxury Line',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(24,	'Fixed Price',	'Volvo',	'XC40',	'Belmore, Sydney (NSW)',	0.00,	22,	14108,	'Average',	2021,	'2023-10-23',	'Petrol',	'Automatic',	'XZ MY22 T4 Inscription Wagon 5dr Spts Auto 8sp AWD 2.0T',	'Wagon',	'4x4',	'Volvo XC40 2021',	'Scrapes ',	'P/Wind, Airbag Side Various, ABS, Airbag Dual, Airbag Side Various, Alloy Wheels, AWD, Cent.Lock, Climate Control, Cru. Cont, GPS Navigation, Keyless Entry, Keyless Start, P/Seats, P/Steer, P/Wind, Park Sensors - Front, Park Sensors - Rear, Radio, Reverse Camera, Traction Control, Turbo, Cent.Lock, P/Steer, ABS, Traction Control',	'Complete Service History',	'Keys',	'Fair',	'Fair',	'Fair',	'Fair',	'Space Saver',	'Blue',	'2.0',	8,	'T4 Inscription',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(25,	'Auction',	'Volvo',	'XC40',	'Belmore, Sydney (NSW)',	0.00,	50,	60978,	'Above Average',	2019,	'2023-10-17',	'Petrol',	'Automatic',	'XZ MY20 T4 Momentum Wagon 5dr Spts Auto 8sp 2.0T',	'Wagon',	'Front Wheel Drive',	'Volvo XC40 2019',	'Minor Paint Chips and Small Scratches Visible ',	'ABS, Traction Control, Cent.Lock, P/Steer, P/Wind, Airbag Side Various, ABS, Airbag Dual, Airbag Side Various, Aircond., Alloy Wheels, Cent.Lock, Climate Control, Cru. Cont, GPS Navigation, Keyless Entry, Keyless Start, P/Seats, P/Steer, P/Wind, Park Sensors - Front, Park Sensors - Rear, Radio, Traction Control, Turbo, Xenon Headlights',	'Complete Service History',	'Keys',	'Good',	'Good',	'Good',	'Good',	'Space Saver',	'Black',	'2.0',	8,	'T4 Momentum',	'Direct Injection',	'Turbo',	'Owner Manual Only',	NULL,	'Motor Vehicles'),
(26,	'Wholesale',	'Volvo',	'XC60',	'Caringbah (NSW)',	0.00,	52,	59910,	'Excellent',	2019,	'2023-11-06',	'Diesel',	'Automatic',	'UZ MY20 D4 Inscription Wagon 5dr Spts Auto 8sp AWD 2.0DTT',	'Wagon',	'4x4',	'Volvo XC60 2019',	NULL,	'Lifestyle Pack,Harmon Kardon Premium Sound',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Blue',	'2.0',	8,	'D4 Inscription',	'Direct Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles'),
(27,	'Dealership',	'Volvo',	'XC70',	'Dudley Park (WA)',	0.00,	197,	220002,	'Excellent',	2007,	'2023-11-08',	'Petrol',	'Automatic',	'MY07 SE Wagon 5dr Spts Auto 5sp 4x4 2.5T',	'Wagon',	'4x4',	'Volvo XC70 2007',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'Grey',	'2.5',	5,	'SE',	'Multi-Point Injection',	'Turbo',	NULL,	NULL,	'Motor Vehicles');

